#!/usr/bin/env python3
import yaml
import time
import sys

from labNetwork import labNetwork

from alivenessReceiver import NAO
from alivenessReceiver import Status


if __name__ == "__main__":
    try:
        with open('/tmp/aliveness.yml', 'r') as yaml_file:
            status = yaml.load(yaml_file)
        # check the age of the aliveness file
        if time.time() - status.timestamp > 20:
            sys.exit(1)
        widgetString = ""
        for robot in status.robots:
            if robot.lan is True or robot.wlan is True:
                widgetString += str(robot.headNumber)
                widgetString += " "
        print(widgetString)
    except IOError as e:
        sys.exit(1)
