#!/bin/bash
if xinput list-props "SynPS/2 Synaptics TouchPad" | grep -E "Device Enabled.*:.*1" > /dev/null
then
  xinput disable "SynPS/2 Synaptics TouchPad"
else
  xinput enable "SynPS/2 Synaptics TouchPad"
fi
